version: '3.7'

x-common-variables:
  - &common_environment_variables
    POSTGRES: ${POSTGRES_HOST}:5432
    MONGO_EC2: ${MONGO_HOST}:27017

services:

  postgres:
    image: postgres:12
    hostname: ${POSTGRES_HOST}
    container_name: ${POSTGRES_HOST}
    ports:
      - '0.0.0.0:${POSTGRES_PORT}:5432'
    networks: ['${NETWORK}']
    volumes: 
      - '${POSTGRES_RESOURCES_PATH}:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always

  mongo:
    image: mongo:4-bionic
    hostname: ${MONGO_HOST}
    container_name: ${MONGO_HOST}
    ports:
      - '0.0.0.0:${MONGO_PORT}:27017'
    networks: ['${NETWORK}']
    volumes: ['${MONGO_RESOURCES_PATH}:/data/db']
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: always

  node-red:
    hostname: ${NODE_RED_HOST}
    container_name: ${NODE_RED_HOST}
    build: ./${NODE_RED_HOST}/${ARCH}
    ports:
      - '0.0.0.0:${NODE_RED_PORT}:1880'
    networks: ['${NETWORK}']
    volumes:
      - ${NODE_RED_RESOURCES_PATH}:/data
    restart: always

  mqtt-broker:
    image: eclipse-mosquitto:1.6.9
    hostname: ${MQTT_BROKER_HOST}
    container_name: ${MQTT_BROKER_HOST}
    ports:
      - '0.0.0.0:${MQTT_BROKER_PORT_1}:1883'
      - '0.0.0.0:${MQTT_BROKER_PORT_2}:9001'
    volumes:
      - ./${MQTT_BROKER_HOST}/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks: [ '${NETWORK}' ]
    restart: always

  mlflow-environment:
    build: ./${MLFLOW_HOST}/mlflow-environment
    hostname: mflow-environment
    container_name: mlflow-environment
    ports:
      - '0.0.0.0:${MLFLOW_PORT_UI}:8990'
      - '0.0.0.0:${MLFLOW_PORT_NOTEBOOK}:8888'
    networks: ['${NETWORK}']
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      MLFLOW_ARTIFACTS_PATH: ${MLFLOW_ARTIFACTS_PATH}
    restart: always

  standalone:
    build: standalone
    hostname: standalone
    container_name: standalone
    ports:
      - '0.0.0.0:${STANDALONE_PORT}:${STANDALONE_PORT}'
    networks: [ '${NETWORK}' ]
    environment:
      <<: *common_environment_variables
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      MONGO_BBDD: admin
      MONGO_USERNAME: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: always

networks:
  franburruezo:
