version: '3.7'

x-common-variables:
  - &common_environment_variables
    POSTGRES: ${POSTGRES_HOST}:5432
    MONGO: ${MONGO_HOST}:27017
    NODERED: ${NODE_RED_HOST}:1880
  - &credentials
    MONGO_USERNAME: francisco
    MONGO_PASSWORD: francisco

services:

  postgres:
    image: postgres:12
    hostname: ${POSTGRES_HOST}
    container_name: ${POSTGRES_HOST}
    ports:
      - '0.0.0.0:${POSTGRES_PORT}:5432'
    networks: ['${NETWORK}']
    volumes: 
      - '${POSTGRES_RESOURCES_PATH}:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: francisco
      POSTGRES_PASSWORD: francisco
    restart: always

  mongo:
    image: mongo:4-bionic
    hostname: ${MONGO_HOST}
    container_name: ${MONGO_HOST}
    ports:
      - '0.0.0.0:${MONGO_PORT}:27017'
    networks: ['${NETWORK}']
    volumes: ['${MONGO_RESOURCES_PATH}:/data/db']
    environment:
      MONGO_INITDB_ROOT_USERNAME: francisco
      MONGO_INITDB_ROOT_PASSWORD: francisco
    restart: always

  node-red:
    hostname: ${NODE_RED_HOST}
    container_name: ${NODE_RED_HOST}
    build: ./${NODE_RED_HOST}/${ARCH}
    ports:
      - '0.0.0.0:${NODE_RED_PORT}:1880'
    networks: ['${NETWORK}']
    volumes:
      - ${NODE_RED_RESOURCES_PATH}:/data
    restart: always

  mlflow-environment:
    build: ./${MLFLOW_HOST}/mlflow-environment
    hostname: mflow-environment
    container_name: mlflow-environment
    ports:
      - '0.0.0.0:${MLFLOW_PORT_UI}:8990'
      - '0.0.0.0:${MLFLOW_PORT_NOTEBOOK}:8888'
    networks: ['${NETWORK}']
    environment:
      MLFLOW_TRACKING_URI: 'postgresql://francisco:francisco@mlflow.c3uusfqnmup4.eu-west-3.rds.amazonaws.com/mlflow'
      MLFLOW_ARTIFACTS_PATH: 's3://mlflow-tfm'
    restart: always

  standalone:
    build: standalone
    hostname: standalone
    container_name: standalone
    ports:
      - '0.0.0.0:${STANDALONE_PORT}:${STANDALONE_PORT}'
    networks: [ '${NETWORK}' ]
    environment:
      MLFLOW_TRACKING_URI: 'postgresql://francisco:francisco@mlflow.c3uusfqnmup4.eu-west-3.rds.amazonaws.com/mlflow'
      MONGO_EC2: 'ec2-15-188-9-114.eu-west-3.compute.amazonaws.com:${MONGO_PORT}'
      MONGO_BBDD: 'admin'
    restart: always

networks:
  franburruezo:
