kind: Template
apiVersion: v1
metadata:
  name: filebeat
  annotations:
    description: Template for filebeat service
    tags: app,python
    iconClass: icon-openshift
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
  spec:
    triggers: []
    strategy:
      type: ${DEPLOYMENT_STRATEGY}
      rollingParams:
        updatePeriodSeconds: "${{ROLLING_UPDATE_PERIOD}}"
        intervalSeconds: "${{ROLLING_INTERVAL}}"
        timeoutSeconds: "${{DEPLOYMENT_TIMEOUT}}"
        maxSurge: "${{ROLLING_MAX_SURGE}}"
        maxUnavailable: "${{ROLLING_MAX_UNAVAILABLE}}"
      recreateParams:
        timeoutSeconds: "${{DEPLOYMENT_TIMEOUT}}"
    replicas: "${{REPLICA_COUNT}}"
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    template:
      metadata:
        name: ${APPLICATION_NAME}
        labels:
          deploymentConfig: ${APPLICATION_NAME}
          app: ${APPLICATION_NAME}
      spec:
        terminationGracePeriodSeconds: 60
        containers:
        - name: ${APPLICATION_NAME}
          image: ${QUAY_URL}/${SERVICE}:${VERSION}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          volumeMounts:
            - name: log
              mountPath: /mnt/log
        serviceAccount: ${APPLICATION_NAME}
        serviceAccountName: ${APPLICATION_NAME}
        volumes:
        - name: log
          persistentVolumeClaim:
            claimName: log
parameters:
- name: APPLICATION_NAME
  description: "The name for the application."
  value: "filebeat"
  required: true
- name: QUAY_URL
  description: URL of the Quay registry to use.
  value: "505799072829.dkr.ecr.eu-west-3.amazonaws.com"
  required: true
- name: SERVICE
  description: "service ID."
  value: "filebeat"
  required: true
- name: VERSION
  description: "Application version to deploy."
  value: "7.6.2"
  required: true
- name: DEPLOYMENT_STRATEGY
  description: "Deployment strategy to use. Values: Recreate, Rolling."
  value: "Rolling"
  required: true
- name: DEPLOYMENT_TIMEOUT
  description: "The time (in seconds) to wait for a scaling event before automatically rolling back to the previous complete deployment."
  value: "600"
  required: true
- name: ROLLING_UPDATE_PERIOD
  description: "The time to wait between individual Pod updates in seconds."
  value: "1"
- name: ROLLING_INTERVAL
  description: "The time to wait between polling the deployment status after update in seconds."
  value: "1"
- name: ROLLING_MAX_SURGE
  description: "The maximum number of Pods that can be scheduled above the original number of Pods expressed in percentage or number of replicas."
  value: "25%"
- name: ROLLING_MAX_UNAVAILABLE
  description: "The maximum number of Pods that can be unavailable during the update expressed in percentage or number of replicas."
  value: "20%"
- name: REPLICA_COUNT
  description: "Number of replicas to run."
  value: "1"
  required: true
- name: CPU_REQUEST
  description: "Minimum amount of CPU that the container may consume. Unit (m) has to be included."
  value: "1m"
  required: true
- name: CPU_LIMIT
  description: "Maximum amount of CPU that the container may consume. Unit (m) has to be included."
  value: "1000m"
  required: true
- name: MEMORY_REQUEST
  description: "Minimum amount of memory that the container may consume. Unit (Mi, Gi) has to be included."
  value: "1Mi"
  required: true
- name: MEMORY_LIMIT
  description: "Maximum amount of memory that the container may consume. Unit (Mi, Gi) has to be included."
  value: "512Mi"
  required: true
labels:
  template: tfm-template-filebeat