apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: log
  name: log
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
